
const songsData = {
    quickPlay: 
           [{ title: "Sandalan", artist: "6cyclemind", src: "6cyclemind - Sandalan (Lyrics).mp3", img: "2.png" },
            { title: "Fly Me To The Moon", artist: "Frank Sinatra", src: "Fly Me To The Moon (2008 Remastered).mp3", img: "46.jpg" },
            { title: "Freaky Friday", artist: "Lil Dicky", src: "Lil Dicky - Freaky Friday (Lyrics) ft. Chris Brown.mp3", img: "8.jpg" },
            { title: "Sun Flower", artist: "Post Malone", src: "Post Malone - Sunflower (Lyrics) ft. Swae Lee.mp3", img: "9.jpg" },
            { title: "Bye Bye Bye", artist: "NSYNC", src: "NSYNC - Bye Bye Bye (Lyrics) (Deadpool 3 Soundtrack).mp3", img: "15.jpg" },
            { title: "Bote at Dyaryo", artist: "Abrakdabra", src: "Bote_t Dyaryo.mp3", img: "4.jpg" },

    ],
    mixedPlayer: [
        { title: "Funkytown", artist: "Lipps Inc.", src: "Lipps Inc. - Funky Town (Lyrics).mp3", img: "12.jpg" },
        { title: "Tokyo Drift", artist: "Teriyaki Boyz", src: "Tokyo Drift (Fast & Furious) (From The Fast And The Furious_ Tokyo Drift Soundtrack).mp3", img: "35.jpg" },
         { title: "Paraluman", artist: "Adie", img: "Paraluman.jpg", src: "Adie - Paraluman (Official Lyric Video).mp3" },
        { title: "Tibok", artist: "Earl Agustin", img: "tibok.jpg", src: "Tibok - Earl Agustin (Performance Video).mp3" },
        { title: "Sa Bawat Sandali", artist: "Amiel Sol", img: "bawat sandali.jpg", src: "Sa Bawat Sandali - Amiel Sol (Visualizer).mp3" },
        { title: "Marilag", artist: "Dionela", img: "marilag.jpg", src: "Dionela - Marilag (Official Lyric Video).mp3" },
    ],
    recommendedSongs: [
        { title: "Luther", artist: " Kendrick Lamar", src: "Kendrick Lamar - luther (Official Audio).mp3", img: "Luther.jpg" },
        { title: "Blue", artist: "Yung Kai", src: "blue (Official Music Video).mp3", img: "Blue.jpg" },
        { title: "Diet With A Smile", artist: "Lady Gaga, Bruno Mars", src: "Lady Gaga, Bruno Mars - Die With A Smile (Official Music Video).mp3", img: "Die With A Smile.jpg" },
        { title: "Birds of a Feather", artist: "Bellie Eilish", src: "Billie Eilish - BIRDS OF A FEATHER (Official Music Video).mp3", img: "birds of a feather.jpg" },
        { title: "APT", artist: "Rose, Bruno Mars", src: "ROSÉ & Bruno Mars - APT..mp3", img: "APT.jpg" },
        { title: "Snooze", artist: "Sza", src: "SZA - Snooze (Audio).mp3", img: "Snooze.jpg" },
    ],
    explore: [
        { title: "Clean Heart", artist: "Perfume Genius", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
        { title: "DOA", artist: "St.Vincent", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
        { title: "Bologna", artist: "Destroyer", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
        { title: "You Said You Were Sorry", artist: "Selena Gomez", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
        { title: "Oganesson", artist: "Tortoise", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
        { title: "Physical", artist: "Dua Lipa Ft. Troye Sivan", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
        { title: "Off To The ESSO", artist: "Aya", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
        { title: "Break Me Down", artist: "Yukimi", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
        { title: "Switch It", artist: "TOKiMONSTA Ft. Cakes da Killa", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
        { title: "Jealousy", artist: "Yeji", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
        { title: "Hop Disco", artist: "Derya Yildririm SimSek", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
        { title: "Disease", artist: "Lady Gaga", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
    ],
    categories: {
        Favorite: [
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
        ],
        MostLiked: [
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
        ],
        Popular: [
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
            { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
        ]
    },
    genres: {
        Disco: [
            { title: "Brother Louie", artist: "Modern Talking", img: "36.jpg", src: "songs/as_it_was.mp3" },
            { title: "Never Gonna Give You Up", artist: "Ricky Astley", img: "37.jpg", src: "songs/as_it_was.mp3" },
            { title: "Sayaw Mga Choy", artist: "Dimas Jap", img: "38.jpg", src: "songs/as_it_was.mp3" },
            { title: "Material Girl", artist: "Madonna", img: "39.jpg", src: "songs/as_it_was.mp3" },
            { title: "Macarena", artist: "Los Del Rio", img: "40.jpg", src: "songs/as_it_was.mp3" },
            { title: "Stayin'Alive", artist: "Bee Gees", img: "101.jpg", src: "songs/as_it_was.mp3" },
            { title: "I Will Survive", artist: "Gloria Gaynor", img: "102.jpg", src: "songs/as_it_was.mp3" },
            { title: "Lee Freak", artist: "Chic", img: "103.jpg", src: "songs/as_it_was.mp3" },
            { title: "Funky Town", artist: "Lipps Inc.", img: "12.jpg", src: "songs/as_it_was.mp3" },
            { title: "Don't Leave Me This Way", artist: "Harry Styles", img: "104.jpg", src: "songs/as_it_was.mp3" },
            { title: "Boogie Wonderland", artist: "Earth, Win & Fire", img: "105.jpg", src: "songs/as_it_was.mp3" },
            { title: "Disco Inferno", artist: "The Trammps", img: "106.jpg", src: "songs/as_it_was.mp3" },
        ],
        Electronic: [
            { title: "Titanium", artist: "David Guetta Ft Sia", img: "51.jpg", src: "songs/bohemian_rhapsody.mp3" },
            { title: "Roses", artist: "The Chainsmokers ft Rozes", img: "52.jpg", src: "songs/as_it_was.mp3" },
            { title: "Valodja", artist: "Shantel", img: "53.jpg", src: "songs/as_it_was.mp3" },
            { title: "Sun Is Up", artist: "Inna", img: "54.jpg", src: "songs/as_it_was.mp3" },
            { title: "Don't You Worry Child", artist: "Black Eyed Peasse, Shakira & David Guetta", img: "55.jpg", src: "songs/as_it_was.mp3" },
            { title: "Levels", artist: "Avicii", img: "107.jpg", src: "songs/as_it_was.mp3" },
            { title: "Animals", artist: "Martin Garrix", img: "120.jpg", src: "songs/as_it_was.mp3" },
            { title: "Strobe", artist: "Deadmau5" , img: "108.jpg", src: "songs/as_it_was.mp3" },
            { title: "Clarity", artist: "Zedd Ft. Foxes", img: "109.jpg", src: "songs/as_it_was.mp3" },
            { title: "Turn Down For What", artist: "Dj Snake & Lil Jon", img: "110.jpg", src: "songs/as_it_was.mp3" },
            { title: "Ghost'n'Stuff", artist: "Deadmau5 ft. Rob Swire", img: "111.jpg", src: "songs/as_it_was.mp3" },
            { title: "Wake Me up", artist: "Avicii", img: "112.jpg", src: "songs/as_it_was.mp3" },
        ],
        Folk: [
            { title: "Here Comes The Sun", artist: "The Beatles", img: "16.jpg", src: "songs/gods_plan.mp3" },
            { title: "Illegal Smile", artist: "John Prine", img: "17.jpg", src: "songs/as_it_was.mp3" },
            { title: "Riptide", artist: "Vance Joy", img: "18.jpg", src: "songs/as_it_was.mp3" },
            { title: "Time In A Bottle", artist: "Jim Croce", img: "19.jpg", src: "songs/as_it_was.mp3" },
            { title: "The Lion's Roar", artist: "First Aid Kit", img: "20.jpg", src: "songs/as_it_was.mp3" },
            { title: "Blowin In The Wind", artist: "Bob Dylan", img: "113.jpg", src: "songs/as_it_was.mp3" },
            { title: "The Sound Of The Silence", artist: "Saimon & Garfunkel", img: "114.jpg", src: "songs/as_it_was.mp3" },
            { title: "Big Yellow Taxi", artist: "Joni Mitchell", img: "115.png", src: "songs/as_it_was.mp3" },
            { title: "Take Me Home, Country Roads", artist: "John Denver", img: "116.jpg", src: "songs/as_it_was.mp3" },
            { title: "Fast Car", artist: "Tracy Chapman", img: "117.jpg", src: "songs/as_it_was.mp3" },
            { title: "Wagon Wheel", artist: "Old Crow Medicine Show", img: "118.png", src: "songs/as_it_was.mp3" },
            { title: "Home", artist: "Edward Sharpe & The Magnetic Zeros", img: "119.png", src: "songs/as_it_was.mp3" },
        ],
        Funk: [
            { "title": "Funk Do Bounce", "artist": "Mc GW", "img": "31.jpg", "src": "songs/funk_do_bounce.mp3" },
            { "title": "Murder In My Mind", "artist": "Kordhell", "img": "32.jpg", "src": "songs/murder_in_my_mind.mp3" },
            { "title": "Glory", "artist": "Jungle", "img": "33.jpg", "src": "songs/glory.mp3" },
            { "title": "Orquestra Maldita", "artist": "Black Alien", "img": "34.jpg", "src": "songs/orquestra_maldita.mp3" },
            { "title": "Tokyo Drift", "artist": "Teriyaki Boyz", "img": "35.jpg", "src": "songs/tokyo_drift.mp3" },
            { "title": "As It Was", "artist": "Harry Styles", "img": "121.png", "src": "songs/as_it_was.mp3" },
            { "title": "Superstition", "artist": "Stevie Wonder", "img": "122.jpg", "src": "songs/superstition.mp3" },
            { "title": "Uptown Funk", "artist": "Mark Ronson ft. Bruno Mars", "img": "123.jpg", "src": "songs/uptown_funk.mp3" },
            { "title": "Give Up The Funk", "artist": "Parliament", "img": "124.jpg", "src": "songs/give_up_the_funk.mp3" },
            { "title": "Get Up (I Feel Like Being a) Sex Machine", "artist": "James Brown", "img": "125.jpg", "src": "songs/get_up_sex_machine.mp3" },
            { "title": "Jungle Boogie", "artist": "Kool & The Gang", "img": "126.jpg", "src": "songs/jungle_boogie.mp3" },
            { "title": "Pick Up The Pieces", "artist": "Average White Band", "img": "127.png", "src": "songs/pick_up_the_pieces.mp3" },
            { "title": "Brick House", "artist": "Commodores", "img": "128.jpg", "src": "songs/brick_house.mp3" },
        ],
        HipHop: [
          { "title": "Low", "artist": "Flo Rida ft. T-Pain", "img": "6.JPG", "src": "songs/low.mp3" },
          { "title": "I'll Be Missing You", "artist": "Puff Daddy ft. Faith Evans & 112", "img": "7.jpg", "src": "songs/missing_you.mp3" },
          { "title": "Freaky Friday", "artist": "Lil Dicky ft. Chris Brown", "img": "8.jpg", "src": "songs/freaky_friday.mp3" },
          { "title": "Sunflower", "artist": "Post Malone & Swae Lee", "img": "9.jpg", "src": "songs/sunflower.mp3" },
          { "title": "Walk on Water", "artist": "Eminem ft. Beyoncé", "img": "10.jpg.jpg", "src": "songs/walk_on_water.mp3" },
          { "title": "As It Was", "artist": "Harry Styles", "img": "121.png", "src": "songs/as_it_was.mp3" },
          { "title": "Sicko Mode", "artist": "Travis Scott ft. Drake", "img": "129.png", "src": "songs/sicko_mode.mp3" },
          { "title": "God's Plan", "artist": "Drake", "img": "130.jpg", "src": "songs/gods_plan.mp3" },
          { "title": "Lose Yourself", "artist": "Eminem", "img": "131.jpg", "src": "songs/lose_yourself.mp3" },
          { "title": "Numb/Encore", "artist": "Jay-Z & Linkin Park", "img": "132.jpg", "src": "songs/numb_encore.mp3" },
          { "title": "HUMBLE.", "artist": "Kendrick Lamar", "img": "133.jpg", "src": "songs/humble.mp3" },
          { "title": "No Role Modelz", "artist": "J. Cole", "img": "134.jpg", "src": "songs/no_role_modelz.mp3" },
          { "title": "Juicy", "artist": "The Notorious B.I.G.", "img": "135.jpeg", "src": "songs/juicy.mp3" },
],
         Jazz: [
          { "title": "Fly Me To The Moon", "artist": "Frank Sinatra", "img": "51.jpg", "src": "songs/fly_me_to_the_moon.mp3" },
          { "title": "From The Start", "artist": "Laufey", "img": "52.jpg", "src": "songs/from_the_start.mp3" },
          { "title": "Dream A Little Dream Of Me", "artist": "Ella Fitzgerald", "img": "53.jpg", "src": "songs/dream_a_little_dream.mp3" },
          { "title": "Songbird", "artist": "Eva Cassidy", "img": "54.jpg", "src": "songs/songbird.mp3" },
          { "title": "My Foolish Heart", "artist": "Bill Evans", "img": "55.jpg", "src": "songs/my_foolish_heart.mp3" },
          { "title": "Take Five", "artist": "Dave Brubeck", "img": "136.jpg", "src": "songs/take_five.mp3" },
          { "title": "What A Wonderful World", "artist": "Louis Armstrong", "img": "137.jpg", "src": "songs/what_a_wonderful_world.mp3" },
          { "title": "Autumn Leaves", "artist": "Nat King Cole", "img": "138.jpg", "src": "songs/autumn_leaves.mp3" },
          { "title": "Misty", "artist": "Erroll Garner", "img": "139.jpg", "src": "songs/misty.mp3" },
          { "title": "Cheek to Cheek", "artist": "Ella Fitzgerald & Louis Armstrong", "img": "140.jpg", "src": "songs/cheek_to_cheek.mp3" },
          { "title": "Blue in Green", "artist": "Miles Davis", "img": "141.jpg", "src": "songs/blue_in_green.mp3" },
          { "title": "In A Sentimental Mood", "artist": "Duke Ellington & John Coltrane", "img": "142.jpg", "src": "songs/in_a_sentimental_mood.mp3" }
],      
     "K-pop": [
          { "title": "Bang Bang Bang", "artist": "BIGBANG", "img": "41.jpeg", "src": "songs/bang_bang_bang.mp3" },
          { "title": "Love Shot", "artist": "EXO", "img": "42.jpg", "src": "songs/love_shot.mp3" },
          { "title": "Super Shy", "artist": "NewJeans", "img": "43.jpg", "src": "songs/super_shy.mp3" },
          { "title": "Gangnam Style", "artist": "PSY", "img": "44.png", "src": "songs/gangnam_style.mp3" },
          { "title": "Gentleman", "artist": "PSY", "img": "45.jpg", "src": "songs/gentleman.mp3" },
          { "title": "As It Was", "artist": "Harry Styles", "img": "121.png", "src": "songs/as_it_was.mp3" },
          { "title": "Pink Venom", "artist": "BLACKPINK", "img": "143.jpeg", "src": "songs/pink_venom.mp3" },
          { "title": "Dynamite", "artist": "BTS", "img": "144.jpg", "src": "songs/dynamite.mp3" },
          { "title": "Hype Boy", "artist": "NewJeans", "img": "145.jpg", "src": "songs/hype_boy.mp3" },
          { "title": "God's Menu", "artist": "Stray Kids", "img": "146.webp", "src": "songs/gods_menu.mp3" },
          { "title": "Feel Special", "artist": "TWICE", "img": "147.jpg", "src": "songs/feel_special.mp3" },
          { "title": "Love Dive", "artist": "IVE", "img": "148.webp", "src": "songs/love_dive.mp3" },
          { "title": "Super", "artist": "SEVENTEEN", "img": "149.jpg", "src": "songs/super.mp3" },

],

        Old: [
         { "title": "You Decorated My Life", "artist": "Kenny Rogers", "img": "21.jpg", "src": "songs/you_decorated_my_life.mp3" },
         { "title": "Against All Odds", "artist": "Phil Collins", "img": "22.jpg", "src": "songs/against_all_odds.mp3" },
         { "title": "Somewhere Only We Know", "artist": "Keane", "img": "23.jpg", "src": "songs/somewhere_only_we_know.mp3" },
         { "title": "Lonely Is The Night", "artist": "Billy Squier", "img": "24.jpg", "src": "songs/lonely_is_the_night.mp3" },
         { "title": "All My Life", "artist": "America", "img": "25.jpg", "src": "songs/all_my_life.mp3" },
         { "title": "Kahit Maputi Na Ang Buhok Ko", "artist": "Rey Valera", "img": "26.jpg", "src": "songs/kahit_maputi.mp3" },
         { "title": "Ako'y Sayo Ika'y Akin Lamang", "artist": "IAXE", "img": "27.jpg", "src": "songs/akoy_sayo.mp3" },
         { "title": "Kasama Kang Tumanda", "artist": "Ogie Alcasid", "img": "28.jpg", "src": "songs/kasama_kang_tumanda.mp3" },
         { "title": "Narda", "artist": "Kamikazee", "img": "29.jpg", "src": "songs/narda.mp3" },
         { "title": "Ikaw Na Nga", "artist": "Willie Revillame", "img": "30.jpg", "src": "songs/ikaw_na_nga.mp3" },
         { "title": "Yesterday", "artist": "The Beatles", "img": "406.jpg", "src": "songs/yesterday.mp3" },
         { "title": "Hotel California", "artist": "Eagles", "img": "407.png", "src": "songs/hotel_california.mp3" },
],
  
      Pop: [
         { "title": "Happy", "artist": "Pharrell Williams", "img": "11.jpg", "src": "songs/happy.mp3" },
         { "title": "Funkytown", "artist": "Lipps Inc.", "img": "12.jpg", "src": "songs/funkytown.mp3" },
         { "title": "Dancing Queen", "artist": "ABBA", "img": "13.png", "src": "songs/dancing_queen.mp3" },
         { "title": "Shape Of You", "artist": "Ed Sheeran", "img": "14.png", "src": "songs/shape_of_you.mp3" },
         { "title": "Bye Bye Bye", "artist": "*NSYNC", "img": "15.jpg", "src": "songs/bye_bye_bye.mp3" },
         { "title": "Uptown Funk", "artist": "Mark Ronson ft. Bruno Mars", "img": "403.jpg", "src": "songs/uptown_funk.mp3" },
         { "title": "Can't Stop The Feeling!", "artist": "Justin Timberlake", "img": "157.jpg", "src": "songs/cant_stop_the_feeling.mp3" },
         { "title": "Blinding Lights", "artist": "The Weekend", "img": "158.jpg", "src": "songs/blinding_lights.mp3" },
         { "title": "Rolling In The Deep", "artist": "Adele", "img": "159.png", "src": "songs/rolling_in_the_deep.mp3" },
         { "title": "Bad Romance", "artist": "Lady Gaga", "img": "160.jpg", "src": "songs/bad_romance.mp3" },
         { "title": "Shake It Off", "artist": "Taylor Swift", "img": "161.jpg", "src": "songs/shake_it_off.mp3" },
         { "title": "Firework", "artist": "Katy Perry", "img": "162.jpg", "src": "songs/firework.mp3" }

],
       Rap: [
        { title: "Fly Baby", artist: "Queen", img: "61.jpg", src: "songs/bohemian_rhapsody.mp3" }, 
        { title: "As It Was", artist: "Harry Styles", img: "121.jpg", src: "songs/as_it_was.mp3" },
        { title: "Puff Me Up", artist: "Supafly", img: "62.jpg", src: "songs/lose_yourself.mp3" },
        { title: "Wag Ipagsabi", artist: "Dreycruz", img: "63.jpg", src: "songs/humble.mp3" },
        { title: "Pasay 2 Qc", artist: "Nazty kidd, Nateman", img: "64.jpg", src: "songs/gods_plan.mp3" },
        { title: "Subomoto", artist: "Zae, Hev Abi", img: "65.jpg", src: "songs/middle_child.mp3" },
        { title: "Sicko Mode", artist: "Travis Scott", img: "163.jpg", src: "songs/sicko_mode.mp3" },
        { title: "Goosebumps", artist: "Travis Scott", img: "164.jpg", src: "songs/goosebumps.mp3" },
        { title: "Stan", artist: "Eminem", img: "165.jpg", src: "songs/stan.mp3" },
        { title: "No Role Modelz", artist: "J. Cole", img: "166.webp", src: "songs/no_role_modelz.mp3" },
        { title: "Money Trees", artist: "Kendrick Lamar", img: "167.jpg", src: "songs/money_trees.mp3" },
        { title: "God's Plan", artist: "Drake", img: "168.png", src: "songs/gods_plan.mp3" }
],

   "Rock": [
        { title: "That Wrong Turn", artist: "Metallica", img: "1.png", src: "songs/enter_sandman.mp3" },
        { title: "Before The Dawn", artist: "Led Zeppelin", img: "2.png", src: "songs/stairway_to_heaven.mp3" },
        { title: "Usok Asin", artist: "Pink Floyd", img: "3.png", src: "songs/comfortably_numb.mp3" },
        { title: "Bote Dyaryo", artist: "Queen", img: "4.png", src: "songs/we_will_rock_you.mp3" },
        { title: "Slash", artist: "Guns N' Roses", img: "5.jpg", src: "songs/sweet_child_o_mine.mp3" },
        { title: "Thunderstruck", artist: "AC/DC", img: "405.jpg", src: "songs/thunderstruck.mp3" },
        { title: "Smells Like Teen Spirit", artist: "Nirvana", img: "169.jpg", src: "songs/smells_like_teen_spirit.mp3" },
        { title: "Hotel California", artist: "Eagles", img: "170.jpg", src: "songs/hotel_california.mp3" },
        { title: "Livin' on a Prayer", artist: "Bon Jovi", img: "171.jpg", src: "songs/livin_on_a_prayer.mp3" },
        { title: "Bohemian Rhapsody", artist: "Queen", img: "172.jpg", src: "songs/bohemian_rhapsody.mp3" },
        { title: "Back in Black", artist: "AC/DC", img: "173.png", src: "songs/back_in_black.mp3" },
        { title: "Highway to Hell", artist: "AC/DC", img: "174.jpg", src: "songs/highway_to_hell.mp3" }
],


    },
    "albums": [
        {
            artist: "Olivia Rodrigo",
            albumImg: "oliviarodrigo.jpg",
            songs: [
                
                { title: "Love Is Embarrassing", artist: "Drake", img: "187.png", src: "songs/gods_plan.mp3" },
                { title: "Vampire", artist: "Harry Styles", img: "188.webp", src: "songs/as_it_was.mp3" },
                { title: "Good 4 U", artist: "Harry Styles", img: "189.png", src: "songs/as_it_was.mp3" },
                { title: "Bad Idea Right?", artist: "Harry Styles", img: "190.jpg", src: "songs/as_it_was.mp3" },
                { title: "Drive License", artist: "Harry Styles", img: "191.jpg", src: "songs/as_it_was.mp3" },
                { title: "Get Him Back", artist: "Harry Styles", img: "192.jpg", src: "songs/as_it_was.mp3" },
                { title: "Deja Vu", artist: "Harry Styles", img: "193.jpg", src: "songs/as_it_was.mp3" },
                { title: "Traitor", artist: "Harry Styles", img: "194.jpg", src: "songs/as_it_was.mp3" },
                { title: "Happier", artist: "Harry Styles", img: "195.jpg", src: "songs/as_it_was.mp3" },
                { title: "Brutal", artist: "Harry Styles", img: "196.jpg", src: "songs/as_it_was.mp3" },
                { title: "Favorite Crime", artist: "Harry Styles", img: "197.jpg", src: "songs/as_it_was.mp3" },
                { title: "Jealousy", artist: "Harry Styles", img: "402.jpg", src: "songs/as_it_was.mp3" },   
            ]
        },
        {
            artist: "Ben & Ben",
            albumImg: "sb19.jpg",
            songs: [
                { title: "Could Be Something", img: "198.jpg", src: "songs/lose_yourself.mp3" },
                { title: "Dear", img: "199.jpg", src: "songs/without_me.mp3" },
                { title: "Fall", artist: "Harry Styles", img: "200.jpg", src: "songs/as_it_was.mp3" },
                { title: "Kasayaw", artist: "Harry Styles", img: "201.jpg", src: "songs/as_it_was.mp3" },
                { title: "Doors", artist: "Harry Styles", img: "202.jpg", src: "songs/as_it_was.mp3" },
                { title: "Pasalubong", artist: "Harry Styles", img: "203.webp", src: "songs/as_it_was.mp3" },
                { title: "Upuan", artist: "Harry Styles", img: "204.jpg", src: "songs/as_it_was.mp3" },
                { title: "Kathang Isip", artist: "Harry Styles", img: "205.jpg", src: "songs/as_it_was.mp3" },
                { title: "Leaves", artist: "Harry Styles", img: "206.jpg", src: "songs/as_it_was.mp3" },
                { title: "Di ka sayang", artist: "Harry Styles", img: "207.png", src: "songs/as_it_was.mp3" },
                { title: "Pagtingin", artist: "Harry Styles", img: "208.jpg", src: "songs/as_it_was.mp3" },
                { title: "Araw-Araw", artist: "Harry Styles", img: "209.jpg", src: "songs/as_it_was.mp3" },
            ]
        },{
            artist: "SB19",
            albumImg: "sb19.jpg",
            songs: [
                { title: "Dam", img: "210.jpg", src: "songs/love_story.mp3" },
                { title: "Gento", img: "211.jpg", src: "songs/you_belong_with_me.mp3" },
                { title: "Mapa", artist: "Harry Styles", img: "212.jpg", src: "songs/as_it_was.mp3" },
                { title: "Bazinga", artist: "Harry Styles", img: "213.jpg", src: "songs/as_it_was.mp3" },
                { title: "Mana", artist: "Harry Styles", img: "214.jpg", src: "songs/as_it_was.mp3" },
                { title: "SLMT", artist: "Harry Styles", img: "215.jpg", src: "songs/as_it_was.mp3" },
                { title: "Go Up", artist: "Harry Styles", img: "216.jpg", src: "songs/as_it_was.mp3" },
                { title: "Ikako", artist: "Harry Styles", img: "217.jpg", src: "songs/as_it_was.mp3" },
                { title: "Freedom", artist: "Harry Styles", img: "218.jpg", src: "songs/as_it_was.mp3" },
                { title: "Alab", artist: "Harry Styles", img: "219.jpg", src: "songs/as_it_was.mp3" },
                { title: "WYAT(Where You At)", artist: "Harry Styles", img: "220.jpg", src: "songs/as_it_was.mp3" },
                { title: "What", artist: "Harry Styles", img: "221.jpg", src: "songs/as_it_was.mp3" },
            ]
        },
        {
            artist: "Syd Hartha",
            albumImg: "syd.jpg",
            songs: [
                { title: "Tila Tala", img: "222.jpg", src: "songs/lose_yourself.mp3" },
                { title: "Iglap", img: "223.jpg", src: "songs/without_me.mp3" },
                { title: "Paru Paro", artist: "Harry Styles", img: "224.jpg", src: "songs/as_it_was.mp3" },
                { title: "Panalangin", artist: "Harry Styles", img: "225.jpg", src: "songs/as_it_was.mp3" },
                { title: "Ayaw", artist: "Harry Styles", img: "226.jpg", src: "songs/as_it_was.mp3" },
                { title: "Gabay", artist: "Harry Styles", img: "227.jpg", src: "songs/as_it_was.mp3" },
                { title: "Pakay", artist: "Harry Styles", img: "228.jpg", src: "songs/as_it_was.mp3" },
                { title: "Lipad", artist: "Harry Styles", img: "229.jpg", src: "songs/as_it_was.mp3" },
                { title: "Hiwaga", artist: "Harry Styles", img: "230.webp", src: "songs/as_it_was.mp3" },
                { title: "Kung Nag-aatubili", artist: "Harry Styles", img: "231.jpg", src: "songs/as_it_was.mp3" },
                { title: "Oro", artist: "Harry Styles", img: "232.jpg", src: "songs/as_it_was.mp3" },
                { title: "Ayaw Mo Naba?", artist: "Harry Styles", img: "234.webp", src: "songs/as_it_was.mp3" },
            ]
        },
        {
            artist: "Bruno Mars",
            albumImg: "brunod.jpg",
            songs: [
                { title: "Just The Way You Are", img: "235.jpg", src: "songs/love_story.mp3" },
                { title: "Grenade", img: "236.jpg", src: "songs/you_belong_with_me.mp3" },
                { title: "Uptown Funk", artist: "Harry Styles", img: "237.jpg", src: "songs/as_it_was.mp3" },
                { title: "When I Was Your Man", artist: "Harry Styles", img: "238.jpg", src: "songs/as_it_was.mp3" },
                { title: "24k Magic", artist: "Harry Styles", img: "239.jpg", src: "songs/as_it_was.mp3" },
                { title: "Treasure", artist: "Harry Styles", img: "240.jpg", src: "songs/as_it_was.mp3" },
                { title: "Talking To The Moon", artist: "Harry Styles", img: "241.jpg", src: "songs/as_it_was.mp3" },
                { title: "Locked Out Of Heaven", artist: "Harry Styles", img: "242.jpg", src: "songs/as_it_was.mp3" },
                { title: "That's What I Like", artist: "Harry Styles", img: "243.jpg", src: "songs/as_it_was.mp3" },
                { title: "Leave The Door Open", artist: "Harry Styles", img: "244.jpg", src: "songs/as_it_was.mp3" },
                { title: "Finesse", artist: "Harry Styles", img: "245.jpg", src: "songs/as_it_was.mp3" },
                { title: "Court On Me", artist: "Harry Styles", img: "246.jpg", src: "songs/as_it_was.mp3" },
            ]
        },
        {
            artist: "Lady Gaga",
            albumImg: "ladygaga.jpg",
            songs: [
                { title: "Poker Face", img: "401.jpg", src: "songs/lose_yourself.mp3" },
                { title: "Bad Romance", img: "247.jpg", src: "songs/without_me.mp3" },
                { title: "Born This Way", artist: "Harry Styles", img: "248.png", src: "songs/as_it_was.mp3" },
                { title: "Just Dance", artist: "Harry Styles", img: "249.png", src: "songs/as_it_was.mp3" },
                { title: "Shawllow", artist: "Harry Styles", img: "250s.jpg", src: "songs/as_it_was.mp3" },
                { title: "Million Reasons", artist: "Harry Styles", img: "251.jpg", src: "songs/as_it_was.mp3" },
                { title: "Always Remember Us This Way", artist: "Harry Styles", img: "252.webp", src: "songs/as_it_was.mp3" },
                { title: "Stupid Love", artist: "Harry Styles", img: "253.avif", src: "songs/as_it_was.mp3" },
                { title: "Applause", artist: "Harry Styles", img: "254.jpg", src: "songs/as_it_was.mp3" },
                { title: "The Edge Of Glory", artist: "Harry Styles", img: "255.jpg", src: "songs/as_it_was.mp3" },
                { title: "Rain On Me", artist: "Harry Styles", img: "256.png", src: "songs/as_it_was.mp3" },
                { title: "Judas", artist: "Harry Styles", img: "257.png", src: "songs/as_it_was.mp3" },
            ]
        },
            {
            artist: "Katy Perry",
            albumImg: "katy.jpg",
            songs: [
                { title: "Roar", img: "258.jpg", src: "songs/love_story.mp3" },
                { title: "Firework", img: "259.jpg", src: "songs/you_belong_with_me.mp3" },
                { title: "Dark Horse", artist: "Harry Styles", img: "260.avif", src: "songs/as_it_was.mp3" },
                { title: "Teenage Dream", artist: "Harry Styles", img: "261.png", src: "songs/as_it_was.mp3" },
                { title: "Last Friday Night (T.G.I.F)", artist: "Harry Styles", img: "262.jpg", src: "songs/as_it_was.mp3" },
                { title: "California Gurls", artist: "Harry Styles", img: "263.jpg", src: "songs/as_it_was.mp3" },
                { title: "E.T", artist: "Harry Styles", img: "264.webp", src: "songs/as_it_was.mp3" },
                { title: "Wide Awake", artist: "Harry Styles", img: "265.jpg", src: "songs/as_it_was.mp3" },
                { title: "The One That Got Away", artist: "Harry Styles", img: "266.jpg", src: "songs/as_it_was.mp3" },
                { title: "Hot n Cold", artist: "Harry Styles", img: "267.jpg", src: "songs/as_it_was.mp3" },
                { title: "Part Of Me", artist: "Harry Styles", img: "268.jpg", src: "songs/as_it_was.mp3" },
                { title: "Never Really Over", artist: "Harry Styles", img: "269.jpg", src: "songs/as_it_was.mp3" },
            ]
        },
         {
           artist: "Earth, Wind & Fire",
           albumImg: "earthwind.jpg",
          songs: [
               { title: "September", img: "270.jpg", src: "songs/september.mp3" },
               { title: "Boogie Wonderland", img: "271.jpg", src: "songs/boogie_wonderland.mp3" },
               { title: "Let's Groove", img: "272.jpg", src: "songs/lets_groove.mp3" },
               { title: "Fantasy", img: "273.jpg", src: "songs/fantasy.mp3" },
               { title: "Shining Star", img: "274.jpg", src: "songs/shining_star.mp3" },
               { title: "Reasons", img: "275.jpg", src: "songs/reasons.mp3" },
               { title: "After the Love Has Gone", img: "276.jpg", src: "songs/after_the_love.mp3" },
               { title: "Sing a Song", img: "277.jpg", src: "songs/sing_a_song.mp3" },
               { title: "That's the Way of the World", img: "278.jpg", src: "songs/thats_the_way.mp3" },
               { title: "Serpentine Fire", img: "279.jpg", src: "songs/serpentine_fire.mp3" },
               { title: "Got to Get You into My Life", img: "280.jpg", src: "songs/got_to_get_you.mp3" },
               { title: "Mighty Mighty", img: "281.jpg", src: "songs/mighty_mighty.mp3" }
        ]
    },
    {
        artist: "Stephen Sanchez",
        albumImg: "step.jpg",
        songs: [
            { title: "Until I Found You", img: "282.jpg", src: "songs/until_i_found_you.mp3" },
            { title: "Evangeline", img: "283.jpg", src: "songs/evangeline.mp3" },
            { title: "See The Light", img: "284.webp", src: "songs/see_the_light.mp3" },
            { title: "Only Girl", img: "285.jpg", src: "songs/only_girl.mp3" },
            { title: "High", img: "286.jpg", src: "songs/high.mp3" },
            { title: "Lady By The Sea", img: "287.jpg", src: "songs/lady_by_the_sea.mp3" },
            { title: "Shake", img: "288.jpg", src: "songs/shake.mp3" },
            { title: "Love Me", img: "289.png", src: "songs/love_me.mp3" },
            { title: "Perfect Love", img: "290.jpg", src: "songs/perfect_love.mp3" },
            { title: "Stay With Me", img: "291.webp", src: "songs/stay_with_me.mp3" },
            { title: "Be More", img: "292.jpg", src: "songs/tell_me.mp3" },
            { title: "The Thing Called Love", img: "293.jpg", src: "songs/golden.mp3" }
        ]
    },
    {
        artist: "Coolio",
        albumImg: "coolio.jpg",
        songs: [
            { title: "Gangsta's Paradise", img: "295.jpg", src: "songs/gangstas_paradise.mp3" },
            { title: "Fantastic Voyage", img: "296.jpg", src: "songs/fantastic_voyage.mp3" },
            { title: "1, 2, 3, 4", img: "297.jpg", src: "songs/1234.mp3" },
            { title: "Too Hot", img: "299.jpg", src: "songs/too_hot.mp3" },
            { title: "C U When U Get There", img: "300.jpg", src: "songs/cu_when_u_get_there.mp3" },
            { title: "The Winner", img: "301.jpg", src: "songs/the_winner.mp3" },
            { title: "Hit 'em High", img: "302.jpg", src: "songs/hit_em_high.mp3" },
            { title: "Ooh La La", img: "303.jpg", src: "songs/ooh_la_la.mp3" },
            { title: "Nature of the Business", img: "305.jpg", src: "songs/nature_of_the_business.mp3" },
            { title: "One More Night", img: "306.jpg", src: "songs/one_more_night.mp3" },
            { title: "Bright as the Sun", img: "307.jpg", src: "songs/bright_as_the_sun.mp3" },
            { title: "Cruisin'", img: "308.jpg", src: "songs/cruisin.mp3" },
        ],
       },
        {
         artist: "Eminem",
         albumImg: "eminem.jpg",
         songs: [
            { title: "Lose Yourself", img: "404.jpg", src: "songs/lose_yourself.mp3" },
            { title: "Stan", img: "images/stan.jpg", src: "songs/stan.mp3" },
            { title: "Without Me", img: "310.jpg", src: "songs/without_me.mp3" },
            { title: "Rap God", img: "309.jpg", src: "songs/rap_god.mp3" },
            { title: "The Real Slim Shady", img: "311.jpg", src: "songs/real_slim_shady.mp3" },
            { title: "Mockingbird", img: "312.jpg", src: "songs/mockingbird.mp3" },
            { title: "Not Afraid", img: "313.jpg", src: "songs/not_afraid.mp3" },
            { title: "Godzilla", img: "314.jpg", src: "songs/godzilla.mp3" },
            { title: "Love the Way You Lie", img: "315.jpg", src: "songs/love_the_way_you_lie.mp3" },
            { title: "Till I Collapse", img: "316.jpg", src: "songs/till_i_collapse.mp3" },
            { title: "Venom", img: "317.jpg", src: "songs/venom.mp3" },
            { title: "Beautiful", img: "313.jpg", src: "songs/beautiful.mp3" },
            ],
        },
        {
          artist: "Ice Cube",
          albumImg: "icecube.jpg",
          songs: [
            { title: "It Was a Good Day", img: "318.jpg", src: "songs/good_day.mp3" },
            { title: "Check Yo Self", img: "319.jpg", src: "songs/check_yo_self.mp3" },
            { title: "No Vaseline", img: "320.jpg", src: "songs/no_vaseline.mp3" },
            { title: "You Know How We Do It", img: "321.jpg", src: "songs/you_know.mp3" },
            { title: "Gangsta Rap Made Me Do It", img: "322.jpg", src: "songs/gangsta_rap.mp3" },
            { title: "Why We Thugs", img: "323.jpg", src: "songs/why_we_thugs.mp3" },
            { title: "Go to Church", img: "324.jpg", src: "songs/go_to_church.mp3" },
            { title: "Bop Gun", img: "325.jpg", src: "songs/bop_gun.mp3" },
            { title: "Pushin' Weight", img: "326.jpg", src: "songs/pushin_weight.mp3" },
            { title: "Today Was a Good Day", img: "327.jpg", src: "songs/today_good_day.mp3" },
            { title: "Steady Mobbin'", img: "328.jpg", src: "songs/steady_mobbin.mp3" },
            { title: "Natural Born Killaz", img: "329.jpg", src: "songs/natural_born_killaz.mp3" },
         ],
     }
  ]
    
};
