
const songsData = {
  quickPlay: 
         [{ title: "Sandalan", artist: "6cyclemind", src: "6cyclemind - Sandalan (Lyrics).mp3", img: "2.png" },
          { title: "Fly Me To The Moon", artist: "Frank Sinatra", src: "Fly Me To The Moon (2008 Remastered).mp3", img: "46.jpg" },
          { title: "Freaky Friday", artist: "Lil Dicky", src: "Lil Dicky - Freaky Friday (Lyrics) ft. Chris Brown.mp3", img: "8.jpg" },
          { title: "Sun Flower", artist: "Post Malone", src: "Post Malone - Sunflower (Lyrics) ft. Swae Lee.mp3", img: "9.jpg" },
          { title: "Bye Bye Bye", artist: "NSYNC", src: "NSYNC - Bye Bye Bye (Lyrics) (Deadpool 3 Soundtrack).mp3", img: "15.jpg" },
          { title: "Bote at Dyaryo", artist: "Abrakdabra", src: "Bote_t Dyaryo.mp3", img: "4.jpg" },

  ],
  mixedPlayer: [
      { title: "Funkytown", artist: "Lipps Inc.", src: "Lipps Inc. - Funky Town (Lyrics).mp3", img: "12.jpg" },
      { title: "Tokyo Drift", artist: "Teriyaki Boyz", src: "Tokyo Drift (Fast & Furious) (From The Fast And The Furious_ Tokyo Drift Soundtrack).mp3", img: "35.jpg" },
       { title: "Paraluman", artist: "Adie", img: "Paraluman.jpg", src: "Adie - Paraluman (Official Lyric Video).mp3" },
      { title: "Tibok", artist: "Earl Agustin", img: "tibok.jpg", src: "Tibok - Earl Agustin (Performance Video).mp3" },
      { title: "Sa Bawat Sandali", artist: "Amiel Sol", img: "bawat sandali.jpg", src: "Sa Bawat Sandali - Amiel Sol (Visualizer).mp3" },
      { title: "Marilag", artist: "Dionela", img: "marilag.jpg", src: "Dionela - Marilag (Official Lyric Video).mp3" },
  ],
  recommendedSongs: [
      { title: "Luther", artist: " Kendrick Lamar", src: "Kendrick Lamar - luther (Official Audio).mp3", img: "Luther.jpg" },
      { title: "Blue", artist: "Yung Kai", src: "blue (Official Music Video).mp3", img: "Blue.jpg" },
      { title: "Diet With A Smile", artist: "Lady Gaga, Bruno Mars", src: "Lady Gaga, Bruno Mars - Die With A Smile (Official Music Video).mp3", img: "Die With A Smile.jpg" },
      { title: "Birds of a Feather", artist: "Bellie Eilish", src: "Billie Eilish - BIRDS OF A FEATHER (Official Music Video).mp3", img: "birds of a feather.jpg" },
      { title: "APT", artist: "Rose, Bruno Mars", src: "ROSÉ & Bruno Mars - APT..mp3", img: "APT.jpg" },
      { title: "Snooze", artist: "Sza", src: "SZA - Snooze (Audio).mp3", img: "Snooze.jpg" },
  ],
  explore: [
      { title: "Clean Heart", artist: "Perfume Genius", img: "411.jpg", src: "Perfume Genius - Clean Heart.mp3" },
      { title: "DOA", artist: "St.Vincent", img: "412.jpg", src: "St. Vincent  DOA (From Death of a Unicorn).mp3" },
      { title: "Bologna", artist: "Destroyer", img: "413.jpg", src: "Destroyer - Bologna (feat. Fiver) (Official Music Video).mp3" },
      { title: "You Said You Were Sorry", artist: "Selena Gomez", img: "414.png", src: "Selena Gomez, benny blanco - You Said You Were Sorry (Official Lyric Video).mp3" },
      { title: "Oganesson", artist: "Tortoise", img: "415.jpg", src: "Tortoise - Oganesson.mp3" },
      { title: "Physical", artist: "Dua Lipa Ft. Troye Sivan", img: "416.jpg", src: "Dua Lipa - Physical (feat. Troye Sivan) (Official Visualiser).mp3" },
      { title: "Off To The ESSO", artist: "Aya", img: "417.jpg", src: "aya, off to the ESSO.mp3" },
      { title: "Break Me Down", artist: "Yukimi", img: "418.jpg", src: "Yukimi - 'Break Me Down' (Official Video).mp3" },
      { title: "Switch It", artist: "TOKiMONSTA Ft. Cakes da Killa", img: "419.jpg", src: "Dua Lipa - Physical (feat. Troye Sivan) (Official Visualiser).mp3" },
      { title: "Abracadabra", artist: "Lady Gaga", img: "500.jpg", src: "Lady Gaga - Abracadabra (Official Music Video).mp3" },
      { title: "Hop Bico", artist: "Derya Yildririm SimSek", img: "501.jpg", src: "Derya Yıldırım & Grup Şimşek - Hop Bico.mp3" },
      { title: "Disease", artist: "Lady Gaga", img: "502.jpg", src: "Lady Gaga - Disease (Official Music Video).mp3" },
  ],
  categories: {
      Favorite: [
          { title: "As It Was", artist: "Harry Styles", img: "121.png", src: "HarryStyles-As It Was.mp3" },
          { title: "Fly Me To The Moon", artist: "Frank Sinatra", src: "Fly Me To The Moon (2008 Remastered).mp3", img: "46.jpg" },
          { title: "Sun Flower", artist: "Post Malone", src: "Post Malone - Sunflower (Lyrics) ft. Swae Lee.mp3", img: "9.jpg" },
          { title: "Paraluman", artist: "Adie", img: "Paraluman.jpg", src: "Adie - Paraluman (Official Lyric Video).mp3" },
          { title: "Tibok", artist: "Earl Agustin", img: "tibok.jpg", src: "Tibok - Earl Agustin (Performance Video).mp3" },
          { title: "Luther", artist: " Kendrick Lamar", src: "Kendrick Lamar - luther (Official Audio).mp3", img: "Luther.jpg" },
          { title: "Blue", artist: "Yung Kai", src: "blue (Official Music Video).mp3", img: "Blue.jpg" },
          { title: "Wake Me up", artist: "Avicii", img: "112.jpg", src: "Avicii - Wake Me Up (Official Lyric Video).mp3" },
          { title: "Here Comes The Sun", artist: "The Beatles", img: "16.jpg", src: "The Beatles - Here Comes The Sun (2019 Mix).mp3" },
          { title: "From The Start", artist: "Laufey", img: "47.jpg", src: "Laufey - From The Start (Official Music Video).mp3" },
          { title: "Super Shy", artist: "NewJeans", img: "43.jpg", src: "Super Shy.mp3" },
          { title: "God's Plan", artist: "Drake", img: "168.png", src: "Drake - God_s Plan (Lyric Video).mp3" },
      ],
      MostLiked: [
          { title: "Clarity", artist: "Zedd Ft. Foxes", img: "109.jpg", src: "Zedd - Clarity ft. Foxes.mp3" },
          { title: "Turn Down For What", artist: "Dj Snake & Lil Jon", img: "110.jpg", src: "DJ Snake, Lil Jon - Turn Down for What.mp3" },
          { title: "Gentleman", artist: "PSY", img: "45.jpg", src: "PSY - GENTLEMAN.mp3" },
          { title: "Drive License", artist: "Olivia Rodrigo", img: "191.jpg", src: "Olivia Rodrigo - drivers license (Official Video).mp3" },
          { title: "Just The Way You Are", artist: "Bruno Mars", img: "235.jpg", src: "Bruno Mars - Just The Way You Are (Official Music Video).mp3" },
          { title: "Bad Romance", artist: "Lady gaga", img: "247.jpg", src: "Lady Gaga - Bad Romance (Official Music Video).mp3" },
          { title: "Roar", artist: "Katy Perry", img: "258.jpg", src: "Katy Perry - Roar.mp3" },
          { title: "September", artist: "Earth, Wind & Fire", img: "270.jpg", src: "Earth, Wind & Fire - September (Official HD Video).mp3" },
          { title: "Until I Found You", artist: "Stephen Sanchez", img: "282.jpg", src: "Stephen Sanchez - Until I Found You (Lyrics).mp3" },
          { title: "Rap God", artist: "Eminem", img: "309.jpg", src: "Rap God - Eminem.mp3" },
          { title: "As It Was", artist: "Harry Styles", img: "images/as_it_was.jpg", src: "songs/as_it_was.mp3" },
          { title: "No Vaseline", artist: "Ice Cube", img: "320.jpg", src: "No Vaseline.mp3" },
      ],
      Popular: [
          { title: "Take Me Home, Country Roads", artist: "John Denver", img: "John Denver", src: "John Denver - Take Me Home, Country Roads (Official Audio).mp3" },
          { title: "Hotel California", artist: "Eagles", img: "407.png", src: "Eagles - Hotel California (Official Audio).mp3" },
          { title: "Yesterday", artist: "The Beatles", img: "406.jpg", src: "The Beatles - Yesterday  (Lyrics).mp3" },
          { title: "Firework", artist: "Katy Perry", img: "162.jpg", src: "Katy Perry - Firework (Lyrics).mp3" },
          { title: "Shake It Off", artist: "Taylor Swift", img: "161.jpg", src: "Taylor Swift - Shake It Off.mp3" },
          { title: "Bad Romance", artist: "Lady Gaga", img: "160.jpg", src: "Lady Gaga - Bad Romance (Official Music Video).mp3" },
          { title: "Rolling In The Deep", artist: "Adele", img: "159.png", src: "Adele - Rolling in the Deep (Official Music Video).mp3" },
          { title: "Highway to Hell", artist: "AC/DC", img: "174.jpg", src: "ACDC - Highway to Hell (Official Video).mp3" },
          { title: "Back in Black", artist: "AC/DC", img: "173.png", src: "ACDC - Back In Black (Official Video).mp3" },
          { title: "Livin' on a Prayer", artist: "Bon Jovi", img: "171.jpg", src: "Bon Jovi - Livin' On A Prayer.mp3" },
          { title: "Dancing Queen", artist: "ABBA", img: "13.png", src: "ABBA - Dancing Queen (Official Lyric Video).mp3" },
          { title: "Smells Like Teen Spirit", artist: "Nirvana", img: "169.jpg", src: "Nirvana - Smells Like Teen Spirit (Official Music Video).mp3" },
      ]
  },
 genres: {
      Disco: [
          { title: "Brother Louie", artist: "Modern Talking", img: "36.jpg", src: "Modern Talking - Brother Louie (lyrics).mp3" },
          { title: "Never Gonna Give You Up", artist: "Ricky Astley", img: "37.jpg", src: "Rick Astley - Never Gonna Give You Up (Official Music Video).mp3" },
          { title: "Material Girl", artist: "Madonna", img: "39.jpg", src: "Madonna - Material Girl (Lyrics).mp3" },
          { title: "Macarena", artist: "Los Del Rio", img: "40.jpg", src: "Los Del Rio - Macarena (Lyrics).mp3" },
          { title: "Stayin'Alive", artist: "Bee Gees", img: "101.jpg", src: "Bee Gees - Stayin' Alive (Official Music Video).mp3" },
          { title: "I Will Survive", artist: "Gloria Gaynor", img: "102.jpg", src: "Gloria Gaynor - I Will Survive (Live From Her Majesty's, 13.10.1985).mp3" },
          { title: "Lee Freak", artist: "Chic", img: "103.jpg", src: "CHIC - Le Freak (Official Music Video).mp3 " },
          { title: "Disco Fever", artist: "VST & Company", img: "12.jpg", src: "Disco Fever (1978) - VST & Company.mp3" },
          { title: "Where Have You Been My Disco", artist: "IV of Spades", img: "104.jpg", src: "Where Have You been My Disco_  IV OF SPADES (Lyrics).mp3" },
          { title: "Awitin Mo, Isasayaw Ko", artist: "VST & Company", img: "105.jpg", src: "Awitin Mo, Isasayaw Ko - VST & Company [Official Lyric Video].mp3" },
          { title: "Hey Barbara", artist: "IV of Spades", img: "106.jpg", src: "IV OF SPADES - Hey Barbara (Official Video).mp3" },
          { title: "Sayaw Mga Choy", artist: "Dimas Jap", img: "38.jpg", src: "discobudots - SAYAW MGA CHOY ( DOYDOY DANCE  MATHEMATICS DANCE CHALLENGE ) ( Budots Remix ).mp3" },
      ],
      Electronic: [
          { title: "Titanium", artist: "David Guetta Ft Sia", img: "51.jpg", src: "David Guetta - Titanium ft. Sia (Official Video).mp3" },
          { title: "Roses", artist: "The Chainsmokers ft Rozes", img: "52.jpg", src: "The Chainsmokers - Roses (Official Audio) ft. ROZES.mp3" },
          { title: "Valodja", artist: "Shantel", img: "53.jpg", src: "Valodja.mp3" },
          { title: "Sun Is Up", artist: "Inna", img: "54.jpg", src: "Inna - Sun Is Up (Ultra Music).mp3" },
          { title: "Don't You Worry Child", artist: "Black Eyed Peasse, Shakira & David Guetta", img: "55.jpg", src: "Swedish House Mafia ft. John Martin - Don_t You Worry Child.mp3" },
          { title: "Levels", artist: "Avicii", img: "107.jpg", src: "Avicii - Levels.mp3" },
          { title: "Animals", artist: "Martin Garrix", img: "120.jpg", src: "Martin Garrix - Animals (Official Video).mp3" },
          { title: "Strobe", artist: "Deadmau5" , img: "108.jpg", src: "deadmau5 - Strobe.mp3" },
          { title: "Clarity", artist: "Zedd Ft. Foxes", img: "109.jpg", src: "Zedd - Clarity ft. Foxes.mp3" },
          { title: "Turn Down For What", artist: "Dj Snake & Lil Jon", img: "110.jpg", src: "DJ Snake, Lil Jon - Turn Down for What.mp3" },
          { title: "Ghost'n'Stuff", artist: "Deadmau5 ft. Rob Swire", img: "111.jpg", src: "deadmau5 feat. Rob Swire - Ghosts N Stuff.mp3" },
          { title: "Wake Me up", artist: "Avicii", img: "112.jpg", src: "Avicii - Wake Me Up (Official Lyric Video).mp3" },
      ],
      Folk: [
          { title: "Here Comes The Sun", artist: "The Beatles", img: "16.jpg", src: "The Beatles - Here Comes The Sun (2019 Mix).mp3" },
          { title: "Illegal Smile", artist: "John Prine", img: "17.jpg", src: "John Prine - Illegal Smile.mp3" },
          { title: "Riptide", artist: "Vance Joy", img: "18.jpg", src: "Vance Joy - Riptide (Lyrics).mp3" },
          { title: "Time In A Bottle", artist: "Jim Croce", img: "19.jpg", src: "Jim Croce - Time In A Bottle.mp3" },
          { title: "The Lion's Roar", artist: "First Aid Kit", img: "20.jpg", src: "First Aid Kit - The Lion's Roar (with lyrics).mp3" },
          { title: "Blowin In The Wind", artist: "Bob Dylan", img: "113.jpg", src: "Bob Dylan - Blowin' in the Wind (Official Audio).mp3" },
          { title: "The Sound Of The Silence", artist: "Saimon & Garfunkel", img: "114.jpg", src: "Simon & Garfunkel - The Sound of Silence (from The Concert in Central Park).mp3" },
          { title: "Big Yellow Taxi", artist: "Joni Mitchell", img: "115.png", src: "Joni Mitchell - Big Yellow Taxi (Official Lyric Video).mp3" },
          { title: "Take Me Home, Country Roads", artist: "John Denver", img: "116.jpg", src: "John Denver - Take Me Home, Country Roads (Official Audio).mp3" },
          { title: "Fast Car", artist: "Tracy Chapman", img: "117.jpg", src: "Tracy Chapman - Fast Car (Official Music Video).mp3" },
          { title: "Wagon Wheel", artist: "Old Crow Medicine Show", img: "118.png", src: "Old Crow Medicine Show - Wagon Wheel [Official Music Video].mp3" },
          { title: "Home", artist: "Edward Sharpe & The Magnetic Zeros", img: "119.png", src: "Edward Sharpe & The Magnetic Zeros - Home (Official Video).mp3" },
      ],
      Funk: [
          { title: "Funk Do Bounce", artist: "Mc GW", img: "31.jpg", src: "Ariis - FUNK DO BOUNCE [Brazilian Funk].mp3" },
          { title: "Murder In My Mind", artist: "Kordhell", img: "32.jpg", src: "KORDHELL - MURDER IN MY MIND.mp3" },
          { title: "Glory", artist: "Jungle", img: "33.jpg", src: "Ogryzek - GLORY (Official Visualiser).mp3" },
          { title: "Orquestra Maldita", artist: "Black Alien", img: "34.jpg", src: "ORQUESTRA MALDITA (BRAZILIAN PHONK).mp3" },
          { title: "Tokyo Drift", artist: "Teriyaki Boyz", img: "35.jpg", src: "Tokyo Drift (Fast & Furious) (From The Fast And The Furious_ Tokyo Drift Soundtrack).mp3" },
          { title: "Superstition", artist: "Stevie Wonder", img: "122.jpg", src: "Stevie Wonder Superstition.mp3" },
          { title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", img: "123.jpg", src: "Mark Ronson - Uptown Funk (Official Video) ft. Bruno Mars.mp3" },
          { title: "Give Up The Funk", artist: "Parliament", img: "124.jpg", src: "Parliament - Give Up The Funk (Tear The Roof Off The Sucker).mp3" },
          { title: "Get Up (I Feel Like Being a) Sex Machine", artist: "James Brown", img: "125.jpg", src: "James Brown   Get up, i feel like being a sex machine.mp3" },
          { title: "Jungle Boogie", artist: "Kool & The Gang", img: "126.jpg", src: "Kool & The Gang - Jungle Boogie (Soul Train 1974).mp3" },
          { title: "Pick Up The Pieces", artist: "Average White Band", img: "127.png", src: "Average White Band - Pick Up The Pieces (1977).mp3" },
          { title: "Brick House", artist: "Commodores", img: "128.jpg", src: "The Commodores-Brick House.mp3" }
      ],
      HipHop: [
        { title: "Low", artist: "Flo Rida ft. T-Pain", img: "6.JPG", src: "Lenny Kravitz - Low (Official Video).mp3" },
        { title: "I'll Be Missing You", artist: "Puff Daddy ft. Faith Evans & 112", img: "7.jpg", src: "Puff Daddy ft. Faith Evans & 112 - I_ll Be Missing You (Lyrics).mp3" },
        { title: "Freaky Friday", artist: "Lil Dicky ft. Chris Brown", img: "8.jpg", src: "Lil Dicky - Freaky Friday (Lyrics) ft. Chris Brown.mp3" },
        { title: "Sunflower", artist: "Post Malone & Swae Lee", img: "9.jpg", src: "Post Malone - Sunflower (Lyrics) ft. Swae Lee.mp3" },
        { title: "Lose Yourself", artist: "Eminem", img: "404.jpg", src: "Eminem - Lose Yourself [HD].mp3" },
        { title: "Sicko Mode", artist: "Travis Scott ft. Drake", img: "129.png", src: "Travis Scott - SICKO MODE ft. Drake.mp3" },
        { title: "God's Plan", artist: "Drake", img: "130.jpg", src: "Drake - God_s Plan (Lyric Video).mp3" },
        { title: "Ice", artist: "ACDMND$", img: "404.jpg", src: "ACDMND$ & Jimmy Pablo - ICE (Official Music Video).mp3" },
        { title: "Zebbiana", artist: "Skusta Clee", img: "132.jpg", src: "Zebbiana - Skusta Clee ( Official Lyrics.mp3" },
        { title: "Miracle Nights", artist: "Almost", img: "133.jpg", src: "Miracle Nights - ALLMOST (BASS BOOSTED  LYRICS).mp3" },
        { title: "Balagbag", artist: "Don Pao", img: "134.jpg", src: "BALAGBAG - Don pao ft Flow G (musiCLyrics).mp3" },
        { title: "Sobrang Solid", artist: "Nik Makino", img: "135.jpeg", src: "Nik Makino - SOBRANG SOLID (feat. NEXXFRIDAY).mp3" }
],
       Jazz: [
        { title: "Fly Me To The Moon", artist: "Frank Sinatra", img: "46.jpg", src: "Fly Me To The Moon (2008 Remastered).mp3" },
        { title: "From The Start", artist: "Laufey", img: "47.jpg", src: "Laufey - From The Start (Official Music Video).mp3" },
        { title: "Dream A Little Dream Of Me", artist: "Ella Fitzgerald", img: "48.jpg", src: "Ella Fitzgerald, Louis Armstrong - Dream A Little Dream Of Me (Audio).mp3" },
        { title: "Songbird", artist: "Eva Cassidy", img: "49.jpg", src: "Kenny G - Songbird (Offiical Video).mp3" },
        { title: "My Foolish Heart", artist: "Bill Evans", img: "50.jpg", src: "Bill Evans-My Foolish Heart.mp3" },
        { title: "Take Five", artist: "Dave Brubeck", img: "136.jpg", src: "Dave Brubeck - Take Five.mp3" },
        { title: "What A Wonderful World", artist: "Louis Armstrong", img: "137.jpg", src: "Louis Armstrong - What A Wonderful World (Official Video).mp3" },
        { title: "Ikaw Lang", artist: "Raffi Quijano", img: "138.jpg", src: "Ikaw Lang.mp3" },
        { title: "Para Sa Akin", artist: "Sitti", img: "139.jpg", src: "Para Sa Akin.mp3" },
        { title: "Chinito", artist: "Yeng Constantino", img: "140.jpg", src: "Chinito - Yeng Constantino (Music Video).mp3" },
        { title: "Sa Mata Makikita", artist: "Roel Cortez", img: "141.jpg", src: "Roel Cortez - Sa Mata Makikita (Official Lyric Video).mp3" },
        { title: "Kabilugan Ng Buwan", artist: "Apo Hiking Society", img: "142.jpg", src: "APO Hiking Society - Kabilugan Ng Buwan (Official Lyric Video).mp3" }
],      
      "K-pop": [
        { title: "Bang Bang Bang", artist: "BIGBANG", img: "41.jpeg", src: "Bang Bang Bang.mp3" },
        { title: "Love Shot", artist: "EXO", img: "42.jpg", src: "Love Shot.mp3" },
        { title: "Super Shy", artist: "NewJeans", img: "43.jpg", src: "Super Shy.mp3" },
        { title: "Gangnam Style", artist: "PSY", img: "44.png", src: "PSY - GANGNAM STYLE.mp3" },
        { title: "Gentleman", artist: "PSY", img: "45.jpg", src: "PSY - GENTLEMAN.mp3" },
        { title: "Pink Venom", artist: "BLACKPINK", img: "143.jpeg", src: "BLACKPINK - Pink Venom MV.mp3" },
        { title: "Dynamite", artist: "BTS", img: "144.jpg", src: "BTS (방탄소년단) 'Dynamite' Official MV.mp3" },
        { title: "Hype Boy", artist: "NewJeans", img: "145.jpg", src: "NewJeans (뉴진스) 'Hype Boy' Official MV (Performance ver.1).mp3" },
        { title: "God's Menu", artist: "Stray Kids", img: "146.webp", src: "Stray Kids 神메뉴(God's Menu) MV.mp3" },
        { title: "Feel Special", artist: "TWICE", img: "147.jpg", src: "TWICE Feel Special MV.mp3" },
        { title: "Love Dive", artist: "IVE", img: "148.webp", src: "IVE 아이브 'LOVE DIVE' MV.mp3" },
        { title: "Super", artist: "SEVENTEEN", img: "149.jpg", src: " SEVENTEEN (세븐틴) '손오공' Official MV.mp3"}

],

      Old: [
       { title: "You Decorated My Life", artist: "Kenny Rogers", img: "21.jpg", src: "Kenny Rogers - You Decorated My Life (Audio).mp3" },
       { title: "Against All Odds", artist: "Phil Collins", img: "22.jpg", src: "Mariah Carey - Against All Odds (Take a Look at Me Now) (Official HD Video) ft. Westlife.mp3" },
       { title: "Somewhere Only We Know", artist: "Keane", img: "23.jpg", src: "Keane - Somewhere Only We Know (Lyrics).mp3" },
       { title: "Lonely Is The Night", artist: "Billy Squier", img: "24.jpg", src: "LONELY IS THE NIGHT -  AIR SUPPLY lyrics.mp3" },
       { title: "All My Life", artist: "America", img: "25.jpg", src: "All My Life.mp3" },
       { title: "Yesterday", artist: "The Beatles", img: "406.jpg", src: "The Beatles - Yesterday  (Lyrics).mp3" },
       { title: "Hotel California", artist: "Eagles", img: "407.png", src: "Eagles - Hotel California (Official Audio).mp3" },
       { title: "Kahit Maputi Na Ang Buhok Ko", artist: "Rey Valera", img: "26.jpg", src: "Rey Valera - Kahit Maputi Na Ang Buhok Ko [Official Lyric Video].mp3" },
       { title: "Ako'y Sayo Ika'y Akin Lamang", artist: "IAXE", img: "27.jpg", src: "Ako_y Sayo Ika_y Akin Lamang - Daniel Padilla (Lyrics)  DJ Greatest Hits.mp3" },
       { title: "Kasama Kang Tumanda", artist: "Ogie Alcasid", img: "28.jpg", src: "KASAMA KANG TUMANDA - DANIEL PADILLA.mp3" },
       { title: "Narda", artist: "Kamikazee", img: "29.jpg", src: "Wille Revillame - Ikaw Na Nga (Official Lyric Video).mp3" },
       { title: "Ikaw Na Nga", artist: "Willie Revillame", img: "30.jpg", src: "Kamikazee - Narda (Official Lyric Video).mp3" }
       
],

    Pop: [
       { title: "Happy", artist: "Pharrell Williams", img: "11.jpg", src: "Happy [From Despicable Me 2] - Pharrell Williams (Lyrics).mp3" },
       { title: "Funkytown", artist: "Lipps Inc.", img: "12.jpg", src: "Lipps Inc. - Funky Town (Lyrics).mp3" },
       { title: "Dancing Queen", artist: "ABBA", img: "13.png", src: "ABBA - Dancing Queen (Official Lyric Video).mp3" },
       { title: "Shape Of You", artist: "Ed Sheeran", img: "14.png", src: "Ed Sheeran - Shape of You (Lyrics).mp3" },
       { title: "Bye Bye Bye", artist: "*NSYNC", img: "15.jpg", src: "NSYNC - Bye Bye Bye (Lyrics) (Deadpool 3 Soundtrack).mp3" },
       { title: "Uptown Funk", artist: "Mark Ronson ft. Bruno Mars", img: "403.jpg", src: "Mark Ronson - Uptown Funk (Official Video) ft. Bruno Mars.mp3" },
       { title: "Can't Stop The Feeling!", artist: "Justin Timberlake", img: "157.jpg", src: "The Weeknd - Blinding Lights (Official Video).mp3" },
       { title: "Sining", artist: "Dionela", img: "158.jpg", src: "Dionela - sining (Lyrics) ft. Jay R.mp3" },
       { title: "Pagsamo", artist: "Arthur Nery", img: "159.png", src: "Arthur Nery - Pagsamo (Lyrics).mp3" },
       { title: "Marilag", artist: "Dionela", img: "marilag.jpg", src: "Dionela - Marilag (Official Lyric Video).mp3" },
       { title: "Rainbow", artist: "South Border", img: "161.jpg", src: "South Border - Rainbow (Lyric).mp3" },
       { title: "Weak", artist: "Michael Pangilinan", img: "162.jpg", src: "Michael Pangilinan - Weak (Cover) Lyrics.mp3" }

],
     Rap: [
      { title: "Sicko Mode", artist: "Travis Scott", img: "163.jpg", src: "Travis Scott - SICKO MODE ft. Drake.mp3" },
      { title: "Goosebumps", artist: "Travis Scott", img: "164.jpg", src: "Travis Scott - goosebumps ft. Kendrick Lamar.mp3" },
      { title: "Stan", artist: "Eminem", img: "165.jpg", src: "Eminem - Stan (Long Version) ft. Dido.mp3" },
      { title: "No Role Modelz", artist: "J. Cole", img: "166.webp", src: "J.Cole - No Role Modelz (Lyrics).mp3" },
      { title: "Money Trees", artist: "Kendrick Lamar", img: "167.jpg", src: "Kendrick Lamar - Money Trees (Feat. Jay Rock).mp3" },
      { title: "God's Plan", artist: "Drake", img: "168.png", src: "Drake - God_s Plan (Lyric Video).mp3" },
      { title: "Fly Baby", artist: "Supafly", img: "61.jpg", src: "Fly Baby - Supafly ft. Sica (Lyrics).mp3" }, 
      { title: "Gayuma", artist: "Abra", img: "121.jpg", src: "Gayuma (Lyrics) - Abra (ft. Thyro & Jeriko Aguilar).mp3" },
      { title: "Puff Me Up", artist: "Supafly", img: "62.jpg", src: "SUPAFLY - PUFF ME UP (Ft. Gat Putch, Gaspari, OG Cry, Ghoti scale, Sica).mp3" },
      { title: "Wag Ipagsabi", artist: "Dreycruz", img: "63.jpg", src: "Dreycruz ft. Bert Symoun - Wag Ipagsabi (Official Music Video).mp3" },
      { title: "Pasay 2 Qc", artist: "Nazty kidd, Nateman", img: "64.jpg", src: "Nazty Kidd - Pasay 2 QC feat. Nateman (Official Music Video).mp3" },
      { title: "Subomoto", artist: "Zae, Hev Abi", img: "65.jpg", src: "Zae, Hev Abi - SUBOMOTO REMIX (Music Video).mp3" }
],

   "Rock": [
      { title: "Before The Dawn", artist: "Judas Priest", img: "2.png", src: "Judas Priest - Before the Dawn (Official Audio).mp3" },
      { title: "Turn the Page", artist: "Metallica", img: "1.png", src:"Metallica_ Turn the Page (Official Music Video).mp3"},
      { title: "Killing Floor", artist: "Slash", img: "5.jpg", src: "Slash feat. Brian Johnson - Killing Floor (Official Music Video).mp3" },
      { title: "Thunderstruck", artist: "AC/DC", img: "405.jpg", src: "ACDC - Thunderstruck (Official Video).mp3" },
      { title: "Smells Like Teen Spirit", artist: "Nirvana", img: "169.jpg", src: "Nirvana - Smells Like Teen Spirit (Official Music Video).mp3" },
      { title: "Hotel California", artist: "Eagles", img: "170.jpg", src: "Eagles - Hotel California (Official Audio).mp3" },
      { title: "Bohemian Rhapsody", artist: "Queen", img: "172.jpg", src: "Queen  Bohemian Rhapsody (Official Video Remastered).mp3" },
      { title: "Ligaya", artist: "Eraserheads", img: "171.jpg", src: "Eraserheads - Ligaya [Lyric Video].mp3" },
      { title: "Kisapmata", artist: "Rivermaya", img: "173.png", src: "Rivermaya - Kisapmata.mp3" },
      { title: "Ang Huling El Bimbo", artist: "Eraserheads", img: "174.jpg", src: "Eraserheads - Ang Huling El Bimbo [Lyric Video].mp3" },
      { title: "Usok", artist: "Asin", img: "3.png", src: "USOK (lyrics) By_ Asin.mp3" },
      { title: "Bote Dyaryo", artist: "Abrakadabra", img: "4.jpg", src: "Bote_t Dyaryo.mp3" },
],



  },
   "albums": [
      {
          artist: "Olivia Rodrigo",
          albumImg: "oliviarodrigo.jpg",
          songs: [
              
              { title: "Love Is Embarrassing", artist: "Olivia Rodrigo", img: "187.png", src: "Olivia Rodrigo - Love Is Embarrassing (Lyrics).mp3" },
              { title: "Vampire", artist: "Olivia Rodrigo", img: "188.webp", src: "Olivia Rodrigo - vampire.mp3" },
              { title: "Good 4 U", artist: "Olivia Rodrigo", img: "189.png", src: "Olivia Rodrigo - good 4 u (Lyrics).mp3" },
              { title: "Bad Idea Right?", artist: "Olivia Rodrigo", img: "190.jpg", src: "Olivia Rodrigo - bad idea right_ (Official Lyric Video).mp3" },
              { title: "Drive License", artist: "Olivia Rodrigo", img: "191.jpg", src: "Olivia Rodrigo - drivers license (Official Video).mp3" },
              { title: "Get Him Back", artist: "Olivia Rodrigo", img: "192.jpg", src: "Olivia Rodrigo - get him back! (Official Lyric Video).mp3" },
              { title: "Deja Vu", artist: "Olivia Rodrigo", img: "193.jpg", src: "Olivia Rodrigo - deja vu (Lyric Video).mp3" },
              { title: "Traitor", artist: "Olivia Rodrigo", img: "192.jpg", src: "Olivia Rodrigo - traitor (Lyric Video).mp3" },
              { title: "Happier", artist: "Olivia Rodrigo", img: "195.jpg", src: "Olivia Rodrigo - happier (Lyric Video).mp3" },
              { title: "Brutal", artist: "Olivia Rodrigo", img: "196.jpg", src: "Olivia Rodrigo - brutal (Lyric Video).mp3" },
              { title: "Favorite Crime", artist: "Olivia Rodrigo", img: "197.jpg", src: "Olivia Rodrigo - favorite crime (Lyric Video).mp3" },
              { title: "Jealousy, Jealousy", artist: "Olivia Rodrigo", img: "402.jpg", src: "Olivia Rodrigo - jealousy, jealousy (Lyric Video).mp3" },   
          ]
      },
      {
          artist: "Ben & Ben",
          albumImg: "benben.jpg",
          songs: [
              { title: "Could Be Something", artist: "Ben & Ben", img: "198.jpg", src: "Ben&Ben - Could Be Something  Official Lyric Video.mp3" },
              { title: "Dear", artist: "Ben & Ben", img: "199.jpg", src: "Dear by Ben&Ben - Dear (Lyrics).mp3" },
              { title: "Fall", artist: "Ben & Ben", img: "200.jpg", src: "Ben&Ben - Fall  Official Music Video.mp3" },
              { title: "Kasayaw", artist: "Ben & Ben", img: "kasayaw.jpg", src: "Ben&Ben - Kasayaw.mp3" },
              { title: "Doors", artist: "Ben & Ben", img: "202.jpg", src: "Ben&Ben - Doors  Official  Lyric Video.mp3" },
              { title: "Pasalubong", artist: "Ben & Ben", img: "203.webp", src: "Ben&Ben, Moira Dela Torre - Pasalubong (feat. Moira Dela Torre).mp3" },
              { title: "Upuan", artist: "Ben & Ben", img: "204.jpg", src: "Ben&Ben - Upuan  Official LYRIC Video.mp3" },
              { title: "Kathang Isip", artist: "Ben & Ben", img: "205.jpg", src: "Kathang Isip.mp3" },
              { title: "Leaves", artist: "Ben & Ben", img: "206.jpg", src: "Ben & Ben - Leaves (Lyrics).mp3" },
              { title: "Di ka sayang", artist: "Ben & Ben", img: "207.png", src: "Ben&Ben - _Di Ka Sayang (Lyric Video).mp3" },
              { title: "Pagtingin", artist: "Ben & Ben", img: "208.jpg", src: "Ben&Ben - Pagtingin  Official Music Video.mp3" },
              { title: "Araw-Araw", artist: "Ben & Ben", img: "209.jpg", src: "Ben&Ben - Araw-Araw (Lyrics).mp3" },
          ]
      },{
          artist: "SB19",
          albumImg: "sb19.jpg",
          songs: [
              { title: "Dam", artist: "SB19", img: "210.jpg", src: "SB19 - DAM.mp3" },
              { title: "Gento", artist: "SB19", img: "211.jpg", src: "SB19 _GENTO_ Lyric Video.mp3" },
              { title: "Mapa", artist: "SB19", img: "212.jpg", src: "SB19 _MAPA_  OFFICIAL LYRIC VIDEO.mp3" },
              { title: "Bazinga", artist: "SB19", img: "213.jpg", src: "SB19 _BAZINGA_  OFFICIAL LYRIC VIDEO.mp3" },
              { title: "Mana", artist: "SB19", img: "214.jpg", src: "SB19 - Mana (Color Coded Lyrics).mp3" },
              { title: "SLMT", artist: "SB19", img: "215.jpg", src: "SB19 _SLMT_ Official Music Video.mp3" },
              { title: "Go Up", artist: "SB19", img: "216.jpg", src: "SB19 - GO UP [OFFICIAL AUDIO].mp3" },
              { title: "Ikako", artist: "SB19", img: "ikako.jpg", src: "[MV] SB19 - ikako.mp3" },
              { title: "Freedom", artist: "SB19", img: "218.jpg", src: "SB19 _FREEDOM_ Lyric Video.mp3" },
              { title: "Alab", artist: "SB19", img: "219.jpg", src: "[Lyric Video] SB19 - ALAB (Burning).mp3" },
              { title: "WYAT(Where You At)", artist: "SB19", img: "220.jpg", src: "SB19 sings 'WYAT (Where You At)'.mp3" },
              { title: "What", artist: "SB19", img: "221.jpg", src: "SB19 'What_' Official MV.mp3" },
          ]
      },
      {
          artist: "Syd Hartha",
          albumImg: "syd.jpg",
          songs: [
              { title: "Tila Tala", artist: "Syd Hartha", img: "222.jpg", src: "tila tala - syd hartha.mp3" },
              { title: "Iglap", artist: "Syd Hartha", img: "223.jpg", src: "iglap - syd hartha (lyric video).mp3" },
              { title: "Paru Paro", artist: "Syd Hartha", img: "224.jpg", src: "syd hartha - paruparo (Lyric Video).mp3" },
              { title: "Panalangin", artist: "Syd Hartha", img: "225.jpg", src: "syd hartha - panalangin (Official Lyric Video).mp3" },
              { title: "Ayaw", artist: "Syd Hartha", img: "226.jpg", src: "syd hartha - ayaw (Official Music Video).mp3" },
              { title: "Gabay", artist: "Syd Hartha", img: "227.jpg", src: "syd hartha - gabay  Official Audio.mp3" },
              { title: "Pakay", artist: "Syd Hartha", img: "228.jpg", src: "syd hartha - pakay  Official Audio.mp3" },
              { title: "Lipad", artist: "Syd Hartha", img: "229.jpg", src: "syd hartha - lipad  Official Audio.mp3" },
              { title: "Hiwaga", artist: "Syd Hartha", img: "230.webp", src: "syd hartha - hiwaga (Official Lyric Video).mp3" },
              { title: "Kung Nag-aatubili", artist: "Syd Hartha", img: "231.jpg", src: "syd hartha - kung nag-aatubili.mp3" },
              { title: "3:15", artist: "Syd Hartha", img: "232.jpg", src: "syd hartha - 3_15 (Official Music Video) ft. Kiyo.mp3" },
              { title: "Damdamin!", artist: "Syd Hartha", img: "234.webp", src: "syd hartha - damdamin! [Official Music Video].mp3" },
          ]
      },
      {
          artist: "Bruno Mars",
          albumImg: "brunod.jpg",
          songs: [
              { title: "Just The Way You Are", artist: "Bruno Mars", img: "235.jpg", src: "Bruno Mars - Just The Way You Are (Official Music Video).mp3" },
              { title: "Grenade", artist: "Bruno Mars", img: "236.jpg", src: "Bruno Mars - Grenade (Official Music Video).mp3" },
              { title: "Uptown Funk", artist: "Bruno Mars", img: "237.jpg", src: "Mark Ronson - Uptown Funk (Official Video) ft. Bruno Mars.mp3" },
              { title: "When I Was Your Man", artist: "Bruno Mars", img: "238.jpg", src: "Bruno Mars - When I Was Your Man (Official Music Video).mp3" },
              { title: "24k Magic", artist: "Bruno Mars", img: "239.jpg", src: "Bruno Mars - 24K Magic (Official Music Video).mp3" },
              { title: "Treasure", artist: "Bruno Mars", img: "240.jpg", src: "Bruno Mars - Treasure (Official Music Video).mp3" },
              { title: "Talking To The Moon", artist: "Bruno Mars", img: "241.jpg", src: "Bruno Mars - Talking To The Moon (Official Lyric Video).mp3" },
              { title: "Locked Out Of Heaven", artist: "Bruno Mars", img: "242.jpg", src: "Bruno Mars - Locked Out Of Heaven (Official Music Video).mp3" },
              { title: "That's What I Like", artist: "Bruno Mars", img: "243.jpg", src: "Bruno Mars - Thats What I Like [Official Music Video].mp3" },
              { title: "Leave The Door Open", artist: "Bruno Mars", img: "244.jpg", src: "Bruno Mars, Anderson .Paak, Silk Sonic - Leave the Door Open [Official Video].mp3" },
              { title: "Finesse", artist: "Bruno Mars", img: "245.jpg", src: "Bruno Mars - Finesse (Remix) (feat. Cardi B) (Official Music Video).mp3" },
              { title: "Count On Me", artist: "Bruno Mars", img: "246.jpg", src: "Bruno Mars - Count on Me (Official Lyric Video).mp3" },
          ]
      },
      {
          artist: "Lady Gaga",
          albumImg: "ladygaga.jpg",
          songs: [
              { title: "Poker Face", artist: "Lady gaga", img: "401.jpg", src: "Lady Gaga - Poker Face (Official Music Video).mp3" },
              { title: "Bad Romance", artist: "Lady gaga", img: "247.jpg", src: "Lady Gaga - Bad Romance (Official Music Video).mp3" },
              { title: "Born This Way", artist: "Lady gaga", img: "248.png", src: "Lady Gaga - Born This Way (Official Music Video).mp3" },
              { title: "Just Dance",  artist: "Lady gaga",img: "249.jpg", src: "Lady Gaga - Just Dance (Official Music Video) ft. Colby O'Donis.mp3" },
              { title: "Shallow", artist: "Lady gaga", img: "250.jpg", src: "Lady Gaga, Bradley Cooper - Shallow (from A Star Is Born) (Official Music Video).mp3" },
              { title: "Million Reasons", artist: "Lady gaga", img: "251.jpg", src: "Lady Gaga - Million Reasons (Official Music Video).mp3" },
              { title: "Always Remember Us This Way", artist: "Lady gaga", img: "252.webp", src: "Lady Gaga - Always Remember Us This Way (from A Star Is Born) (Official Music Video).mp3" },
              { title: "Stupid Love", artist: "Lady gaga", img: "253.avif", src: "Lady Gaga - Stupid Love (Official Music Video).mp3" },
              { title: "Applause", artist: "Lady gaga", img: "254.jpg", src: "Lady Gaga - Applause.mp3" },
              { title: "The Edge Of Glory", artist: "Lady gaga", img: "255.jpg", src: "Lady Gaga - The Edge Of Glory (Official Music Video).mp3" },
              { title: "Rain On Me", artist: "Lady gaga", img: "256.png", src: "Lady Gaga, Ariana Grande - Rain On Me (Official Music Video).mp3" },
              { title: "Judas", artist: "Lady gaga", img: "257.png", src: "Lady Gaga - Judas (Official Music Video).mp3" },
          ]
      },
          {
          artist: "Katy Perry",
          albumImg: "katy.jpg",
          songs: [
              { title: "Roar", artist: "Katy Perry", img: "258.jpg", src: "Katy Perry - Roar.mp3" },
              { title: "Firework", artist: "Katy Perry", img: "259.jpg", src: "Katy Perry - Firework (Lyrics).mp3" },
              { title: "Dark Horse", artist: "Katy Perry", img: "260.avif", src: "Katy Perry - Dark Horse ft. Juicy J.mp3" },
              { title: "Teenage Dream", artist: "Katy Perry", img: "261.png", src: "Katy Perry - Teenage Dream (Official Music Video).mp3" },
              { title: "Last Friday Night (T.G.I.F)", artist: "Katy Perry", img: "262.jpg", src:"Katy Perry - Last Friday Night (T.G.I.F) [Lyrics].mp3" },
              { title: "E.T", artist: "Katy Perry", img: "264.webp", src: "Katy Perry - E.T. (Audio).mp3" },
              { title: "Wide Awake", artist: "Katy Perry", img: "265.jpg", src: "Katy Perry - Wide Awake (Official Video).mp3" },
              { title: "The One That Got Away", artist: "Katy Perry", img: "266.jpg", src: "Katy Perry - The One That Got Away.mp3" },
              { title: "Hot n Cold", artist: "Katy Perry", img: "267.jpg", src: "Katy Perry - Hot N Cold (Official Music Video).mp3" },
              { title: "Part Of Me", artist: "Katy Perry", img: "268.jpg", src: "Katy Perry - Part Of Me (Official).mp3" },
              { title: "Never Really Over", artist: "Katy Perry", img: "269.jpg", src: "Katy Perry - Never Really Over (Official Video).mp3" },
              {title: "Cry About It Later", artist: "katy Perry", img: "601.jpg", src: "Katy Perry - Cry About It Later (The Smile Video Series).mp3"},
          ]
      },
       {
         artist: "Earth, Wind & Fire",
         albumImg: "earthwind.jpg",
        songs: [
             { title: "September", artist: "Earth, Wind & Fire", img: "270.jpg", src: "Earth, Wind & Fire - September (Official HD Video).mp3" },
             { title: "Boogie Wonderland", artist: "Earth, Wind & Fire", img: "271.jpg", src: "Earth, Wind & Fire - Boogie Wonderland (Official Video).mp3" },
             { title: "Let's Groove", artist: "Earth, Wind & Fire", img: "272.jpg", src: "Earth, Wind & Fire - Let's Groove (Official HD Video).mp3" },
             { title: "Fantasy", artist: "Earth, Wind & Fire", img: "273.jpg", src: "Earth, Wind & Fire - Fantasy (Official Audio).mp3" },
             { title: "Shining Star", artist: "Earth, Wind & Fire", img: "274.jpg", src: "Earth, Wind & Fire - Shining Star (Official Audio).mp3" },
             { title: "Reasons", artist: "Earth, Wind & Fire", img: "275.jpg", src: "Earth, Wind & Fire - Reasons (Official Audio).mp3" },
             { title: "After the Love Has Gone", artist: "Earth, Wind & Fire", img: "276.jpg", src: "Earth, Wind & Fire - After The Love Has Gone (Audio).mp3" },
             { title: "Sing a Song", artist: "Earth, Wind & Fire", img: "277.jpg", src: "Earth, Wind & Fire - Sing a Song (Official Audio).mp3" },
             { title: "That's the Way of the World", artist: "Earth, Wind & Fire", img: "278.jpg", src: "Earth, Wind & Fire - That's the Way of the World (Official Audio).mp3" },
             { title: "Serpentine Fire", artist: "Earth, Wind & Fire", img: "279.jpg", src: "Earth, Wind & Fire - Serpentine Fire (Official Video).mp3" },
             { title: "Got to Get You into My Life", artist: "Earth, Wind & Fire", img: "280.jpg", src: "Earth, Wind & Fire - Got to Get You Into My Life (Audio).mp3" },
             { title: "Mighty Mighty", artist: "Earth, Wind & Fire", img: "281.jpg", src: "Earth, Wind & Fire - Mighty Mighty (Official Audio).mp3" }
      ]
  },
  {
      artist: "Stephen Sanchez",
      albumImg: "step.jpg",
      songs: [
          { title: "Until I Found You", artist: "Stephen Sanchez", img: "282.jpg", src: "Stephen Sanchez - Until I Found You (Lyrics).mp3" },
          { title: "Evangeline", artist: "Stephen Sanchez", img: "283.jpg", src: "Stephen Sanchez_ Evangeline  The Tonight Show Starring Jimmy Fallon.mp3" },
          { title: "See The Light", artist: "Stephen Sanchez", img: "284.webp", src: "Stephen Sanchez - See The Light (Live at WFUV).mp3" },
          { title: "Only Girl", artist: "Stephen Sanchez", img: "285.jpg", src: "Stephen Sanchez - Only girl (Lyrics).mp3" },
          { title: "High", artist: "Stephen Sanchez", img: "286.jpg", src: "High (LIVE) - Stephen Sanchez.mp3" },
          { title: "Lady By The Sea", artist: "Stephen Sanchez", img: "287.jpg", src: "Stephen Sanchez - Lady by the Sea.mp3" },
          { title: "Shake", artist: "Stephen Sanchez", img: "288.jpg", src: "Stephen Sanchez - Shake (Amazon Music Live).mp3" },
          { title: "Love life", artist: "Stephen Sanchez", img: "289.png", src: "Stephen Sanchez - Love Life (Official Audio).mp3" },
          { title: "The Pool", artist: "Stephen Sanchez", img: "290.jpg", src: "Stephen Sanchez - The Pool (Official Audio).mp3" },
          { title: "No One Knows", artist: "Stephen Sanchez", img: "291.webp", src: "Stephen Sanchez, Laufey - No One Knows (Lyric Video).mp3" },
          { title: "Be More", artist: "Stephen Sanchez", img: "292.jpg", src: "STEPHEN SANCHEZ - BE MORE (VMA'S 2023).mp3" },
          { title: "The Thing Called Love", artist: "Stephen Sanchez", img: "293.jpg", src: "Stephen Sanchez - This Thing Called Love (Lyric Video) [9yyKV3ylbEg].mp3" }
      ]
  },
  {
      artist: "Coolio",
      albumImg: "coolio.jpg",
      songs: [
          { title: "Gangsta's Paradise", artist: "Coolio", img: "295.jpg", src: "Gangsta's Paradise.mp3" },
          { title: "Fantastic Voyage", artist: "Coolio", img: "296.jpg", src: "Fantastic Voyage.mp3" },
          { title: "1, 2, 3, 4", artist: "Coolio", img: "297.jpg", src: "Coolio - 1234 (Mr. Ness Flip).mp3" },
          { title: "Too Hot", artist: "Coolio", img: "299.jpg", src: "Too Hot (feat. Moneybagg Yo).mp3" },
          { title: "C U When U Get There", artist: "Coolio", img: "300.jpg", src: "C U When U Get There (feat. 40 Thevz).mp3" },
          { title: "The Winner", artist: "Coolio", img: "301.jpg", src: "Coolio - The Winner (Space Jam Soundtrack).mp3" },
          { title: "Hit 'em High", artist: "Coolio", img: "302.jpg", src: "Hit Em' High (Monstars Anthem) - B Real, Busta Rhymes, Coolio, LL Cool J & Method Man.mp3" },
          { title: "Ooh La La", artist: "Coolio", img: "303.jpg", src: "Ooh La La.mp3" },
          { title: "Nature of the Business", artist: "Coolio", img: "305.jpg", src: "Nature of the Business.mp3" },
          { title: "One More Night", artist: "Coolio", img: "300.jpg", src: "COOLIO Feat. LV One More Night.mp3" },
          { title: "Bright as the Sun", artist: "Coolio", img: "301.jpg", src: "Bright as the Sun.mp3" },
          { title: "Cruisin'", artist: "Coolio", img: "303.jpg", src: "Cruisin'.mp3" },
      ],
     },
      {
       artist: "Eminem",
       albumImg: "eminem.jpg",
       songs: [
          { title: "Lose Yourself", artist: "Eminem", img: "404.jpg", src: "Eminem - Lose Yourself [HD].mp3" },
          { title: "Stan", artist: "Eminem", img: "307.jpg", src: "Eminem - Stan (Long Version) ft. Dido.mp3" },
          { title: "Without Me", artist: "Eminem", img: "310.jpg", src: "Without Me.mp3" },
          { title: "Rap God", artist: "Eminem", img: "309.jpg", src: "Rap God - Eminem.mp3" },
          { title: "The Real Slim Shady", artist: "Eminem", img: "311.jpg", src: "Eminem - The Real Slim Shady (Official Video - Clean Version) [eJO5HU_7_1w].mp3" },
          { title: "Mockingbird", artist: "Eminem", img: "312.jpg", src: "Mockingbird.mp3" },
          { title: "Not Afraid", artist: "Eminem", img: "313.jpg", src: "Eminem - Im Not Affraid (Tony Magnifico Remix).mp3" },
          { title: "Godzilla", artist: "Eminem", img: "314.jpg", src: "Godzilla (feat. Juice WRLD).mp3" },
          { title: "Love the Way You Lie", artist: "Eminem", img: "315.jpg", src: "Eminem - Love The Way You Lie.mp3" },
          { title: "Till I Collapse", artist: "Eminem", img: "316.jpg", src: "Till I Collapse [Obim8BYGnOE].mp3" },
          { title: "Venom", artist: "Eminem", img: "317.jpg", src: "Eminem - Venom.mp3" },
          { title: "Beautiful", artist: "Eminem", img: "313.jpg", src: "Eminem - Beautiful (Official Music Video) [lgT1AidzRWM].mp3" },
          ],
      },
      {
        artist: "Ice Cube",
        albumImg: "icecube.jpg",
        songs: [
          { title: "It Was a Good Day", artist: "Ice Cube", img: "318.jpg", src: "Ice Cube - It Was A Good Day [h4UqMyldS7Q].mp3" },
          { title: "Check Yo Self", artist: "Ice Cube", img: "319.jpg", src: "Ice Cube - Check Yo Self (Remix) (Official Music Video) [bueFTrwHFEs].mp3" },
          { title: "No Vaseline", artist: "Ice Cube", img: "320.jpg", src: "No Vaseline.mp3" },
          { title: "You Know How We Do It", artist: "Ice Cube", img: "321.jpg", src: "Ice Cube - You Know How We Do It [rzRqEWJYwX4].mp3" },
          { title: "Gangsta Rap Made Me Do It", artist: "Ice Cube", img: "322.jpg", src: "Gangsta Rap Made Me Do It [8zQFIMhg5YU].mp3" },
          { title: "Why We Thugs", artist: "Ice Cube", img: "323.jpg", src: "02 - Ice Cube - Why We Thugs [8i4SOQJ4P8I] (1).mp3" },
          { title: "Go to Church", artist: "Ice Cube", img: "324.jpg", src: "Ice Cube ft.Snoop Dogg & Lil Jon - Go To Church (Dirty) (Music Video) HD [jsrjD5UGT0M].mp3" },
          { title: "Bop Gun", artist: "Ice Cube", img: "325.jpg", src: "Ice Cube, George Clinton - Bop Gun (One Nation) (Official Music Video) [DjsvqQUcqCs].mp3" },
          { title: "Pushin' Weight", artist: "Ice Cube", img: "326.jpg", src: "01 - Ice Cube - Pushin' Weight (feat. Mr. Shokhop) [k8LcB0TEuwQ].mp3" },
          { title: "Today Was a Good Day", artist: "Ice Cube", img: "327.jpg", src: "Ice Cube - Today Was A Good Day.mp3" },
          { title: "Steady Mobbin'", artist: "Ice Cube", img: "328.jpg", src: "Steady Mobbin'.mp3" },
          { title: "Natural Born Killaz", artist: "Ice Cube", img: "329.jpg", src: "Dr Dre Ft Ice Cube - Natural Born Killaz.mp3" },
       ],
   }
]
  
};
